;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Melee",DevComment="")
+GameplayTagList=(Tag="Ability.Melee.Light",DevComment="")
+GameplayTagList=(Tag="Attr.Energy",DevComment="能量属性")
+GameplayTagList=(Tag="Attr.HP",DevComment="生命属性")
+GameplayTagList=(Tag="Attr.MP",DevComment="法力属性")
+GameplayTagList=(Tag="Cost.Energy",DevComment="能量消耗")
+GameplayTagList=(Tag="Cost.HP",DevComment="HP消耗")
+GameplayTagList=(Tag="Cost.MP",DevComment="MP消耗")
+GameplayTagList=(Tag="Effect.Buff",DevComment="增益效果")
+GameplayTagList=(Tag="Effect.Damage",DevComment="伤害效果")
+GameplayTagList=(Tag="Effect.Heal",DevComment="治疗效果")
+GameplayTagList=(Tag="Skill.HeavyAttack",DevComment="重攻击技能标签")
+GameplayTagList=(Tag="Skill.LightAttack",DevComment="轻攻击技能标签")
+GameplayTagList=(Tag="Target.Area",DevComment="范围目标")
+GameplayTagList=(Tag="Target.Enemy",DevComment="敌方目标")
+GameplayTagList=(Tag="Target.Self",DevComment="自身目标")

