// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace FrontendGameplayTags
{
	//Frontend widget stack
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_Modal);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_GameMenu);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_HUD);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_FrontEnd);
	
	//Frontend widgets
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_PressAnyKeyScreen);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_MainMenuScreen);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_ConfirmScreen);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_StoryScreen);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_GameHUDScreen);
	
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_OptionScreen);
	
	//Frontend Options Image
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_Image_TestImage);

	// Skill system tags
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_LightAttack);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_HeavyAttack);

	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Damage);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Heal);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Buff);

	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost_HP);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost_MP);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost_Energy);

	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Self);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Enemy);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Area);

	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attr_HP);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attr_MP);
	FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attr_Energy);
}
